version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./data/env.grafana
    user: "root"
    volumes:
      - ./data:/var/lib/grafana